package archfile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mohammad-safakhou/diffmind/internal/catalog"
	"github.com/mohammad-safakhou/diffmind/internal/model"
	"gopkg.in/yaml.v3"
)

// generatedHeader marks the machine-owned staging file. It is a transient
// proposal: MergeIntoMain folds its new entries into the human-owned main file
// and then consumes it.
const generatedHeader = "# DO NOT EDIT — generated by DiffMind.\n" +
	"# This is a transient proposal of discovered facts. Review it, then run\n" +
	"# `diffmind catalog merge-file` to fold new entries into your main file.\n"

// derivedDetailKeys are written by extraction.EnrichEntityGrouping but are never
// read back by it, so they are dropped on export to keep authored YAML clean.
// Identity is unaffected: ToModel re-derives them on read.
var derivedDetailKeys = map[string]bool{
	"operation_normalized": true,
	"operation_kind":       true,
	"instance":             true,
}

// Document renders the whole catalog as a discovery file. Used for a first
// scaffold (no file yet) and by the round-trip guarantee test.
func Document(doc catalog.Document) *rawFile {
	return fromRecords(doc.Exposures, doc.Dependencies, doc.Connections)
}

// Marshal serializes a rawFile to YAML bytes (schema header first).
func Marshal(raw *rawFile) ([]byte, error) {
	return yaml.Marshal(raw)
}

// WriteGenerated emits, into generatedPath, the automation-owned records that
// are not already present (by semantic identity) in the human-authored main
// file. Returns the number of records written. When nothing is new it removes a
// stale generated file and returns 0.
func WriteGenerated(doc catalog.Document, mainPath, generatedPath string) (int, error) {
	proposal, err := computeProposal(doc, mainPath)
	if err != nil {
		return 0, err
	}
	count := proposal.Count()
	if count == 0 {
		_ = os.Remove(generatedPath)
		return 0, nil
	}
	raw := fromRecords(proposal.Exposures, proposal.Dependencies, proposal.Connections)
	body, err := Marshal(raw)
	if err != nil {
		return 0, err
	}
	out := append([]byte(generatedHeader), body...)
	if err := writeFileAtomic(generatedPath, out); err != nil {
		return 0, err
	}
	return count, nil
}

// WriteProposalDoc writes a complete proposal document to generatedPath. It is
// used by the repo-centric UI's run -> file workflow, where the selected run is
// compared directly against the repository's diffmind.yaml instead of first
// flowing through the global catalog. Dangling connections are dropped so the
// generated file always resolves cleanly.
func WriteProposalDoc(doc catalog.Document, generatedPath string) error {
	doc.Connections = dropDanglingConnections(doc.Exposures, doc.Dependencies, doc.Connections)
	body, err := Marshal(Document(doc))
	if err != nil {
		return err
	}
	out := append([]byte(generatedHeader), body...)
	return WriteRaw(generatedPath, out)
}

func dropDanglingConnections(exps []model.Exposure, deps []model.Dependency, conns []model.Connection) []model.Connection {
	exposureIDs := map[string]bool{}
	dependencyIDs := map[string]bool{}
	for _, e := range exps {
		exposureIDs[e.ID] = true
	}
	for _, d := range deps {
		dependencyIDs[d.ID] = true
	}
	out := make([]model.Connection, 0, len(conns))
	for _, c := range conns {
		if exposureIDs[c.FromExposureID] && dependencyIDs[c.ToDependencyID] {
			out = append(out, c)
		}
	}
	return out
}

// Proposal is the set of automation-owned records that would be written to the
// transient generated file: those not already present (by semantic identity) in
// the human-authored main file.
type Proposal struct {
	Exposures    []model.Exposure   `json:"exposures"`
	Dependencies []model.Dependency `json:"dependencies"`
	Connections  []model.Connection `json:"connections"`
}

// Count is the total number of records in the proposal.
func (p Proposal) Count() int {
	return len(p.Exposures) + len(p.Dependencies) + len(p.Connections)
}

// computeProposal is the pure (no-write) core of WriteGenerated; it also backs
// the propose-preview endpoint so the UI can show a diff before anything is
// written.
func computeProposal(doc catalog.Document, mainPath string) (Proposal, error) {
	mainEntities, mainConns, err := fileIdentities(mainPath)
	if err != nil {
		return Proposal{}, err
	}

	baseByID := map[string]model.BaseEntity{}
	var p Proposal
	for _, e := range doc.Exposures {
		baseByID[e.ID] = e.BaseEntity
		if doc.Records[e.ID].Owner != catalog.OwnerAutomation {
			continue
		}
		if mainEntities[catalog.EntityCatalogKey("exposure", e.BaseEntity)] {
			continue
		}
		p.Exposures = append(p.Exposures, e)
	}
	for _, d := range doc.Dependencies {
		baseByID[d.ID] = d.BaseEntity
		if doc.Records[d.ID].Owner != catalog.OwnerAutomation {
			continue
		}
		if mainEntities[catalog.EntityCatalogKey("dependency", d.BaseEntity)] {
			continue
		}
		p.Dependencies = append(p.Dependencies, d)
	}

	emitted := map[string]bool{}
	for _, e := range p.Exposures {
		emitted[e.ID] = true
	}
	for _, d := range p.Dependencies {
		emitted[d.ID] = true
	}
	for _, c := range doc.Connections {
		if doc.Records[c.ID].Owner != catalog.OwnerAutomation {
			continue
		}
		// Keep the generated file self-contained: only connections whose both
		// endpoints are also emitted here.
		if !emitted[c.FromExposureID] || !emitted[c.ToDependencyID] {
			continue
		}
		if mainConns[connSemanticKey(baseByID, c)] {
			continue
		}
		p.Connections = append(p.Connections, c)
	}
	return p, nil
}

// ProposalPreview computes, without writing, the records that WriteGenerated
// would emit for this catalog against the given main file.
func ProposalPreview(doc catalog.Document, mainPath string) (Proposal, error) {
	return computeProposal(doc, mainPath)
}

// MergeIntoMain folds new entries from the generated file into the main file's
// node tree, preserving its comments, ordering, and variables, then removes the
// generated file. Entries already present in main (by semantic identity) are
// skipped, so the operation is a no-op on a second run. Returns the number of
// appended records.
func MergeIntoMain(mainPath, generatedPath string) (int, error) {
	comp, found, err := computeMergePlan(mainPath, generatedPath)
	if err != nil || !found {
		return 0, err
	}
	appended := len(comp.appends)
	if appended > 0 {
		for _, a := range comp.appends {
			appendSequenceItem(comp.root, a.section, a.node)
		}
		out, err := yaml.Marshal(&comp.mainDoc)
		if err != nil {
			return 0, err
		}
		if err := writeFileAtomic(mainPath, out); err != nil {
			return 0, err
		}
	}
	if err := os.Remove(generatedPath); err != nil && !os.IsNotExist(err) {
		return appended, err
	}
	return appended, nil
}

// MergePlan describes what a merge would do, by readable identity, so the UI can
// preview it before applying.
type MergePlan struct {
	Append []PlanEntry `json:"append"`
	Skip   []PlanEntry `json:"skip"`
}

// PlanEntry names one record involved in a merge.
type PlanEntry struct {
	Kind    string `json:"kind"` // exposure | dependency | connection
	Name    string `json:"name"`
	Service string `json:"service,omitempty"`
}

type plannedAppend struct {
	section string
	node    *yaml.Node
}

// mergeComputation is the pure result of planning a merge: the plan (for
// preview) plus the node tree and the appends needed to apply it.
type mergeComputation struct {
	plan    MergePlan
	mainDoc yaml.Node
	root    *yaml.Node
	appends []plannedAppend
}

// MergePreview computes, without applying, which generated entries would be
// appended to the main file versus skipped as already present.
func MergePreview(mainPath, generatedPath string) (MergePlan, error) {
	comp, found, err := computeMergePlan(mainPath, generatedPath)
	if err != nil || !found {
		return MergePlan{}, err
	}
	return comp.plan, nil
}

// computeMergePlan is the pure (no-write) core of MergeIntoMain. It keeps the
// intra-proposal dedup-set mutation that MergeIntoMain relied on, so the preview
// append count equals what an apply would write. found is false when there is no
// generated file (a no-op).
func computeMergePlan(mainPath, generatedPath string) (*mergeComputation, bool, error) {
	if _, err := os.Stat(generatedPath); err != nil {
		if os.IsNotExist(err) {
			return nil, false, nil
		}
		return nil, false, err
	}

	genResolved, err := Resolve(generatedPath)
	if err != nil {
		return nil, false, err
	}
	genRaw, err := parse(generatedPath)
	if err != nil {
		return nil, false, err
	}

	comp := &mergeComputation{}
	mainEntities := map[string]bool{}
	mainConns := map[string]bool{}
	if b, err := os.ReadFile(mainPath); err == nil {
		if err := yaml.Unmarshal(b, &comp.mainDoc); err != nil {
			return nil, false, fmt.Errorf("parse %s: %w", mainPath, err)
		}
		mainEntities, mainConns, err = fileIdentities(mainPath)
		if err != nil {
			return nil, false, err
		}
	} else if !os.IsNotExist(err) {
		return nil, false, err
	}
	if comp.mainDoc.Kind == 0 || len(comp.mainDoc.Content) == 0 {
		comp.mainDoc = newDocumentNode(genResolved.Service)
	}
	comp.root = comp.mainDoc.Content[0]

	in, err := ToModel(genResolved, "merge")
	if err != nil {
		return nil, false, err
	}
	baseByID := map[string]model.BaseEntity{}
	for _, e := range in.Exposures {
		baseByID[e.ID] = e.BaseEntity
	}
	for _, d := range in.Dependencies {
		baseByID[d.ID] = d.BaseEntity
	}

	// Index generated raw nodes so we append the original node (comments/shape
	// intact), not a re-marshaled copy.
	expNodes := sequenceItems(genRaw.rootMapping(), "exposures")
	depNodes := sequenceItems(genRaw.rootMapping(), "dependencies")
	connNodes := sequenceItems(genRaw.rootMapping(), "connections")

	for i, e := range in.Exposures {
		entry := PlanEntry{Kind: "exposure", Name: e.Name, Service: e.Service}
		key := catalog.EntityCatalogKey("exposure", e.BaseEntity)
		if mainEntities[key] {
			comp.plan.Skip = append(comp.plan.Skip, entry)
			continue
		}
		comp.appends = append(comp.appends, plannedAppend{"exposures", nodeAt(expNodes, i)})
		comp.plan.Append = append(comp.plan.Append, entry)
		mainEntities[key] = true
	}
	for i, d := range in.Dependencies {
		entry := PlanEntry{Kind: "dependency", Name: d.Name, Service: d.Service}
		key := catalog.EntityCatalogKey("dependency", d.BaseEntity)
		if mainEntities[key] {
			comp.plan.Skip = append(comp.plan.Skip, entry)
			continue
		}
		comp.appends = append(comp.appends, plannedAppend{"dependencies", nodeAt(depNodes, i)})
		comp.plan.Append = append(comp.plan.Append, entry)
		mainEntities[key] = true
	}
	for i, c := range in.Connections {
		entry := PlanEntry{Kind: "connection", Name: connName(baseByID, c)}
		key := connSemanticKey(baseByID, c)
		if mainConns[key] {
			comp.plan.Skip = append(comp.plan.Skip, entry)
			continue
		}
		comp.appends = append(comp.appends, plannedAppend{"connections", nodeAt(connNodes, i)})
		comp.plan.Append = append(comp.plan.Append, entry)
		mainConns[key] = true
	}
	return comp, true, nil
}

func connName(baseByID map[string]model.BaseEntity, c model.Connection) string {
	from := baseByID[c.FromExposureID].Name
	to := baseByID[c.ToDependencyID].Name
	return from + " → " + to
}

// fileIdentities resolves a discovery file and returns the semantic-identity
// sets of its entities and connections. A missing file yields empty sets.
func fileIdentities(path string) (entities map[string]bool, conns map[string]bool, err error) {
	entities = map[string]bool{}
	conns = map[string]bool{}
	if _, statErr := os.Stat(path); statErr != nil {
		if os.IsNotExist(statErr) {
			return entities, conns, nil
		}
		return nil, nil, statErr
	}
	resolved, err := Resolve(path)
	if err != nil {
		return nil, nil, err
	}
	in, err := ToModel(resolved, "identities")
	if err != nil {
		return nil, nil, err
	}
	baseByID := map[string]model.BaseEntity{}
	for _, e := range in.Exposures {
		baseByID[e.ID] = e.BaseEntity
		entities[catalog.EntityCatalogKey("exposure", e.BaseEntity)] = true
	}
	for _, d := range in.Dependencies {
		baseByID[d.ID] = d.BaseEntity
		entities[catalog.EntityCatalogKey("dependency", d.BaseEntity)] = true
	}
	for _, c := range in.Connections {
		conns[connSemanticKey(baseByID, c)] = true
	}
	return entities, conns, nil
}

// connSemanticKey identifies a connection by the semantic identity of its
// endpoints (not by durable IDs), so it is comparable across the catalog
// document and a resolved file.
func connSemanticKey(baseByID map[string]model.BaseEntity, c model.Connection) string {
	from := catalog.EntityCatalogKey("exposure", baseByID[c.FromExposureID])
	to := catalog.EntityCatalogKey("dependency", baseByID[c.ToDependencyID])
	return from + "=>" + to + "|" + strings.ToLower(strings.TrimSpace(c.PathSignature))
}

func fromRecords(exps []model.Exposure, deps []model.Dependency, conns []model.Connection) *rawFile {
	raw := &rawFile{Schema: Schema}

	// Pick a file-level default service when one value dominates.
	serviceCounts := map[string]int{}
	for _, e := range exps {
		serviceCounts[e.Service]++
	}
	for _, d := range deps {
		serviceCounts[d.Service]++
	}
	defaultService := ""
	best := 0
	for svc, n := range serviceCounts {
		if svc != "" && n > best {
			defaultService, best = svc, n
		}
	}
	raw.Service = defaultService

	// Build readable connection tokens: entity Name when unique, else durable ID.
	nameCounts := map[string]int{}
	for _, e := range exps {
		nameCounts[e.Name]++
	}
	for _, d := range deps {
		nameCounts[d.Name]++
	}
	referenced := map[string]bool{}
	for _, c := range conns {
		referenced[c.FromExposureID] = true
		referenced[c.ToDependencyID] = true
	}
	tokenFor := map[string]string{}
	build := func(b model.BaseEntity) rawEntity {
		token := b.Name
		alias := ""
		if nameCounts[b.Name] > 1 {
			token = b.ID
			alias = b.ID
		}
		tokenFor[b.ID] = token

		details := map[string]any{}
		for k, v := range b.Details {
			if derivedDetailKeys[k] {
				continue
			}
			details[k] = v
		}
		if len(details) == 0 {
			details = nil
		}
		svc := b.Service
		if svc == defaultService {
			svc = ""
		}
		re := rawEntity{Type: b.Type, Name: b.Name, Service: svc, Summary: b.Summary, Platform: b.Platform, Details: details, Tags: b.Tags}
		if referenced[b.ID] && alias != "" {
			re.ID = alias
		}
		return re
	}

	for _, e := range exps {
		raw.Exposures = append(raw.Exposures, build(e.BaseEntity))
	}
	for _, d := range deps {
		raw.Dependencies = append(raw.Dependencies, build(d.BaseEntity))
	}
	for _, c := range conns {
		raw.Connections = append(raw.Connections, rawConn{
			From:      tokenFor[c.FromExposureID],
			To:        tokenFor[c.ToDependencyID],
			Condition: conditionShorthand(c.Condition),
			Summary:   c.Summary,
		})
	}
	return raw
}

func conditionShorthand(c model.Condition) string {
	if c.Kind == "" || c.Kind == "unconditional" {
		return ""
	}
	expr := strings.TrimSpace(c.Expression)
	if expr == "" || expr == "true" {
		return ""
	}
	return expr
}

// --- yaml.Node helpers -----------------------------------------------------

func newDocumentNode(service string) yaml.Node {
	root := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "schema"},
		&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: Schema},
	)
	if service != "" {
		root.Content = append(root.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "service"},
			&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: service},
		)
	}
	return yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}
}

// sequenceItems returns the item nodes of the named top-level sequence, or nil.
func sequenceItems(root *yaml.Node, key string) []*yaml.Node {
	seq := findValue(root, key)
	if seq == nil || seq.Kind != yaml.SequenceNode {
		return nil
	}
	return seq.Content
}

func nodeAt(nodes []*yaml.Node, i int) *yaml.Node {
	if i >= 0 && i < len(nodes) {
		return nodes[i]
	}
	return nil
}

func findValue(root *yaml.Node, key string) *yaml.Node {
	if root.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(root.Content); i += 2 {
		if root.Content[i].Value == key {
			return root.Content[i+1]
		}
	}
	return nil
}

// appendSequenceItem appends item to the named top-level sequence, creating the
// sequence (and its key) if absent.
func appendSequenceItem(root *yaml.Node, key string, item *yaml.Node) {
	if item == nil {
		return
	}
	seq := findValue(root, key)
	if seq == nil {
		seq = &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
		root.Content = append(root.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key},
			seq,
		)
	}
	seq.Content = append(seq.Content, item)
}

// WriteRaw atomically writes raw discovery-file bytes to path (used by the
// inline editor). Callers should Validate first.
func WriteRaw(path string, b []byte) error {
	return writeFileAtomic(path, b)
}

func writeFileAtomic(path string, b []byte) error {
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".archfile-*.tmp")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name)
	if _, err := tmp.Write(b); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(name, path)
}
