package verifier

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
	"time"

	"diffmind/internal/consolidation"
)

func verify(bundle consolidation.IntelligenceBundle, opts Options) (consolidation.IntelligenceBundle, Report, error) {
	if opts.PromoteThreshold <= 0 || opts.PromoteThreshold > 1 {
		return consolidation.IntelligenceBundle{}, Report{}, fmt.Errorf("promote threshold must be in (0,1]")
	}
	if opts.DisputeThreshold <= 0 || opts.DisputeThreshold > 1 {
		return consolidation.IntelligenceBundle{}, Report{}, fmt.Errorf("dispute threshold must be in (0,1]")
	}
	if opts.DisputeThreshold > opts.PromoteThreshold {
		return consolidation.IntelligenceBundle{}, Report{}, fmt.Errorf("dispute threshold cannot exceed promote threshold")
	}

	out := make([]consolidation.Entity, 0, len(bundle.Entities))
	decisions := make([]consolidation.Entity, 0, len(bundle.Entities)/2)
	report := Report{
		GeneratedAt:     time.Now().UTC(),
		SnapshotID:      bundle.SnapshotID,
		VerifierID:      verifierID,
		VerifierVersion: verifierVersion,
		InputEntities:   len(bundle.Entities),
	}

	for _, e := range bundle.Entities {
		entity := e
		if entity.Attributes == nil {
			entity.Attributes = map[string]any{}
		}
		status, reason := classifyEntity(entity, opts)
		entity.Attributes["verification_status"] = status
		entity.Attributes["verification_reason"] = reason
		entity.Attributes["verified_by"] = verifierID
		entity.Attributes["verified_at_utc"] = report.GeneratedAt.Format(time.RFC3339)
		out = append(out, entity)

		switch status {
		case "verified":
			report.VerifiedCount++
		case "needs_review":
			report.NeedsReviewCount++
			if entity.Confidence < opts.PromoteThreshold {
				report.UnresolvedLowConfidence++
			}
		case "disputed":
			report.DisputedCount++
			report.UnresolvedLowConfidence++
		}

		if status == "needs_review" || status == "disputed" {
			decision := buildDecisionEntity(bundle.SnapshotID, entity, status, reason, report.GeneratedAt)
			decisions = append(decisions, decision)
		}
	}

	report.DecisionEntitiesAdded = len(decisions)
	total := len(bundle.Entities)
	if total > 0 {
		report.UnresolvedLowConfidenceRate = float64(report.UnresolvedLowConfidence) / float64(total)
	}

	out = append(out, decisions...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].Type == out[j].Type {
			return out[i].NaturalKey < out[j].NaturalKey
		}
		return out[i].Type < out[j].Type
	})

	verified := consolidation.IntelligenceBundle{
		SnapshotID:  bundle.SnapshotID,
		GeneratedAt: time.Now().UTC(),
		Entities:    out,
	}
	report.OutputEntities = len(out)
	return verified, report, nil
}

func classifyEntity(e consolidation.Entity, opts Options) (string, string) {
	if strings.EqualFold(e.Type, "Conflict") {
		return "disputed", "conflict entity requires adjudication"
	}
	if strings.EqualFold(e.Type, "VerificationDecision") {
		return "verified", "decision entity generated by verifier"
	}
	if e.Confidence >= opts.PromoteThreshold {
		return "verified", "confidence above promote threshold"
	}
	if e.Confidence < opts.DisputeThreshold {
		return "disputed", "confidence below dispute threshold"
	}
	return "needs_review", "confidence in review band"
}

func buildDecisionEntity(snapshotID string, subject consolidation.Entity, status string, reason string, now time.Time) consolidation.Entity {
	naturalKey := strings.Join([]string{
		subject.Type,
		subject.ID,
		status,
		reason,
	}, "|")
	return consolidation.Entity{
		ID:         stableEntityID(snapshotID, "VerificationDecision", naturalKey),
		Type:       "VerificationDecision",
		NaturalKey: naturalKey,
		Attributes: map[string]any{
			"subject_entity_id":   subject.ID,
			"subject_entity_type": subject.Type,
			"status":              status,
			"reason":              reason,
			"verifier_id":         verifierID,
			"verifier_version":    verifierVersion,
			"created_at_utc":      now.Format(time.RFC3339),
		},
		EvidenceIDs: append([]string(nil), subject.EvidenceIDs...),
		FactIDs:     append([]string(nil), subject.FactIDs...),
		Confidence:  0.8,
	}
}

func stableEntityID(snapshotID string, entityType string, naturalKey string) string {
	h := sha256.New()
	_, _ = h.Write([]byte(snapshotID))
	_, _ = h.Write([]byte("|"))
	_, _ = h.Write([]byte(entityType))
	_, _ = h.Write([]byte("|"))
	_, _ = h.Write([]byte(naturalKey))
	return hex.EncodeToString(h.Sum(nil))
}
